version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create docs directory
          command: mkdir -p docs
      - run:
          name: Copy assets
          command: cp -r assets/* docs
      - run:
          name: Create page
          command: npm start
      - run:
          name: Post to gh-pages
          command: curl ci-cd.net/v1/gh/pages | bash -s docs/.
workflows:
  version: 2
  website:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
